# Generated by Django 5.0.1 on 2024-01-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleankeralas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='s_serial',
            new_name='s_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='r_report',
        ),
        migrations.AddField(
            model_name='books',
            name='toilet_by_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_by_serial', to='cleankeralas.searchtoilets'),
        ),
    ]
