# Generated by Django 5.0.1 on 2024-01-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleankeralas', '0002_rename_s_serial_books_s_name_remove_books_r_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200)),
                ('r_phone', models.CharField(max_length=10)),
                ('r_email', models.EmailField(max_length=254)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleankeralas.searchtoilets')),
            ],
        ),
    ]
