# Generated by Django 5.0.1 on 2024-01-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleankeralas', '0003_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='t_by_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_by_serial', to='cleankeralas.searchtoilets'),
        ),
    ]
