# Generated by Django 5.0.1 on 2024-01-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleankeralas', '0004_reports_t_by_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='t_report',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
