# Generated by Django 5.0.1 on 2024-01-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleankeralas', '0005_books_t_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='t_report',
        ),
        migrations.AddField(
            model_name='reports',
            name='t_report',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
